#!/usr/bin/env python3
"""Generate a default 128x160 boot splash header (main/boot_image.h).

Pure standard-library Python (no Pillow) so the build always has a splash even
without a user-supplied boot_image.png. Run automatically by the Makefile when
no boot_image.png is present and the header is missing.
"""
import os
import sys

W, H = 128, 160


def rgb565(r, g, b):
    r = max(0, min(255, int(r)))
    g = max(0, min(255, int(g)))
    b = max(0, min(255, int(b)))
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


# Minimal 5x7 glyphs (columns, LSB = top) for the caption text.
FONT = {
    ' ': [0, 0, 0, 0, 0], '.': [0, 0x60, 0x60, 0, 0],
    '0': [0x3E, 0x51, 0x49, 0x45, 0x3E], '1': [0, 0x42, 0x7F, 0x40, 0],
    '2': [0x42, 0x61, 0x51, 0x49, 0x46], '8': [0x36, 0x49, 0x49, 0x49, 0x36],
    'T': [1, 1, 0x7F, 1, 1], 'V': [0x1F, 0x20, 0x40, 0x20, 0x1F],
    'F': [0x7F, 9, 9, 9, 1],
}


def build_pixels():
    img = [[(0, 0, 0) for _ in range(W)] for _ in range(H)]
    cx, cy = W / 2, H / 2
    for y in range(H):
        for x in range(W):
            t = y / H
            r, g, b = 18 + 40 * t, 130 - 90 * t, 150 - 70 * t
            if (int(abs(x - cx) + abs(y - cy)) // 9) % 2 == 0:
                r, g, b = r + 45, g + 30, b + 30
            img[y][x] = (r, g, b)
    for y in range(H):
        for x in range(W):
            if x < 3 or x >= W - 3 or y < 3 or y >= H - 3:
                img[y][x] = (10, 210, 190)

    def text(s, ox, oy, scale, col):
        px = ox
        for ch in s:
            g = FONT.get(ch, FONT[' '])
            for c in range(5):
                for row in range(7):
                    if g[c] & (1 << row):
                        for a in range(scale):
                            for bb in range(scale):
                                X, Y = px + c * scale + a, oy + row * scale + bb
                                if 0 <= X < W and 0 <= Y < H:
                                    img[Y][X] = col
            px += (5 + 1) * scale

    for y in range(66, 96):
        for x in range(6, W - 6):
            img[y][x] = (8, 20, 30)
    text("T10 V2.0", 12, 70, 2, (255, 255, 255))
    text("1.8 TFT", 30, 100, 1, (120, 230, 220))
    return img


def main():
    out = sys.argv[sys.argv.index("-o") + 1] if "-o" in sys.argv else \
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "main", "boot_image.h")

    img = build_pixels()
    data = bytearray()
    for y in range(H):
        for x in range(W):
            r, g, b = img[y][x]
            c = rgb565(r, g, b)
            data.append((c >> 8) & 0xFF)
            data.append(c & 0xFF)

    lines = [
        "// Default boot splash (generated by tools/gen_default_boot.py).",
        "// Gitignored and regenerated by the build; replace by dropping a",
        "// boot_image.png (128x160) in the project folder.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define BOOT_IMAGE_W %d" % W,
        "#define BOOT_IMAGE_H %d" % H,
        "",
        "static const uint8_t boot_image[BOOT_IMAGE_W * BOOT_IMAGE_H * 2] = {",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("Wrote %s (%d bytes, default splash)" % (out, len(data)))


if __name__ == "__main__":
    main()
