#!/usr/bin/env bash
# Regenerate main/accel_schema.h from tools/accel.proto.
# Needs `protoc` (brew install protobuf). Run manually when the schema changes;
# the generated header is committed so the normal build has no protoc dependency.
set -euo pipefail
cd "$(dirname "$0")/.."
protoc --descriptor_set_out=/tmp/accel.desc --proto_path=tools tools/accel.proto
python3 - <<'PY'
data = open('/tmp/accel.desc','rb').read()
out = []
out.append('// AUTO-GENERATED by tools/gen_schema.sh from tools/accel.proto -- do not edit.')
out.append('// Serialized google.protobuf.FileDescriptorSet describing vibration.AccelBatch,')
out.append('// embedded as the MCAP Schema.data so Foxglove can decode the protobuf messages.')
out.append('#pragma once')
out.append('#include <stdint.h>')
out.append('')
out.append('#define ACCEL_SCHEMA_NAME "vibration.AccelBatch"')
out.append('')
out.append('static const uint8_t accel_schema_fds[] = {')
line = '    '
for i, b in enumerate(data):
    line += '0x%02x,' % b
    if (i % 12) == 11:
        out.append(line)
        line = '    '
if line.strip():
    out.append(line)
out.append('};')
out.append('static const uint32_t accel_schema_fds_len = sizeof(accel_schema_fds);')
out.append('')
open('main/accel_schema.h','w').write('\n'.join(out) + '\n')
print('wrote main/accel_schema.h (%d descriptor bytes)' % len(data))
PY
