#!/usr/bin/env python3
"""Convert an image to a C header for the ST7735 boot splash.

Usage:
    pip install pillow
    python3 tools/img2c.py my_logo.png            # -> main/boot_image.h
    python3 tools/img2c.py my_logo.png -o main/boot_image.h

The image is resized/cropped to 128x160 (the panel size) and written as a
big-endian RGB565 byte array named `boot_image`, ready to stream to the display.
"""
import argparse
import os
import sys

W, H = 128, 160


def main():
    ap = argparse.ArgumentParser(description="Image -> ST7735 RGB565 C header")
    ap.add_argument("image", help="source image (png/jpg/...)")
    ap.add_argument("-o", "--output", default=None,
                    help="output header path (default: main/boot_image.h next to this repo)")
    ap.add_argument("--fit", choices=["cover", "contain"], default="cover",
                    help="cover = fill+crop (default), contain = fit+letterbox")
    ap.add_argument("--rotate", type=int, default=0,
                    help="rotate degrees CCW before fitting (0/90/180/270)")
    args = ap.parse_args()

    try:
        from PIL import Image, ImageOps
    except ImportError:
        sys.exit("Pillow is required:  pip install pillow")

    out = args.output
    if out is None:
        here = os.path.dirname(os.path.abspath(__file__))
        out = os.path.join(here, "..", "main", "boot_image.h")

    img = Image.open(args.image).convert("RGB")
    if args.rotate:
        img = img.rotate(args.rotate, expand=True)

    if args.fit == "cover":
        img = ImageOps.fit(img, (W, H), method=Image.LANCZOS)
    else:  # contain: fit inside, pad with black
        img.thumbnail((W, H), Image.LANCZOS)
        bg = Image.new("RGB", (W, H), (0, 0, 0))
        bg.paste(img, ((W - img.width) // 2, (H - img.height) // 2))
        img = bg

    px = img.load()
    data = bytearray()
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y]
            c = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data.append((c >> 8) & 0xFF)
            data.append(c & 0xFF)

    write_header(out, data, args.image)
    print(f"Wrote {out} ({len(data)} bytes, {W}x{H})")


def write_header(path, data, src):
    lines = []
    lines.append("// Auto-generated by tools/img2c.py from " + os.path.basename(src))
    lines.append("// 128x160 RGB565, big-endian byte pairs (hi,lo per pixel).")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define BOOT_IMAGE_W {W}")
    lines.append(f"#define BOOT_IMAGE_H {H}")
    lines.append("")
    lines.append("static const uint8_t boot_image[BOOT_IMAGE_W * BOOT_IMAGE_H * 2] = {")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
