#!/usr/bin/env python3
"""Convert audio_clips/*.wav into main/audio_clips.h for on-device DAC playback.

Each WAV (any rate / width / mono-or-stereo) is converted to 8-bit UNSIGNED,
mono, 16 kHz PCM -- the format the ESP32 DAC plays back -- and emitted as a C
array. Uses only the Python standard library (wave + audioop).

Run by `make audio` (and every build); regenerates the header unconditionally,
but only rewrites the file when its contents change (to avoid needless rebuilds).
"""
import audioop
import glob
import math
import os
import re
import struct
import sys
import wave

RATE = 16000

# Tone shaping (tune these, or pass --lowpass / --gain on the command line):
#   LOWPASS_HZ: gently shave harsh highs above this (0 = off). Lower = warmer,
#               but too low muffles speech. ~4800 just takes the edge off.
#   NORMALIZE : scale each clip so its peak hits this fraction of full-scale.
LOWPASS_HZ = 3800   # voice sits ~300-3400 Hz; this trims hiss without muffling
NORMALIZE = 0.95


def lowpass(samples, cutoff, fs):
    """Single one-pole low-pass (~6 dB/oct) -- a gentle de-harsh."""
    if cutoff <= 0 or cutoff >= fs / 2:
        return samples
    a = 1.0 - math.exp(-2.0 * math.pi * cutoff / fs)
    out = list(samples)
    y = 0.0
    for i, x in enumerate(out):
        y += a * (x - y)
        out[i] = y
    return out


def normalize(samples, target):
    peak = max((abs(s) for s in samples), default=0)
    if peak == 0 or target <= 0:
        return samples
    g = (target * 32767.0) / peak
    return [s * g for s in samples]


def sanitize(name):
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if not ident or ident[0].isdigit():
        ident = "_" + ident
    return ident


def convert(path, cutoff, norm):
    with wave.open(path, "rb") as w:
        ch, sw, fr, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
        frames = w.readframes(n)
    if sw != 2:
        frames = audioop.lin2lin(frames, sw, 2)   # -> 16-bit
    if ch == 2:
        frames = audioop.tomono(frames, 2, 0.5, 0.5)
    if fr != RATE:
        frames, _ = audioop.ratecv(frames, 2, 1, fr, RATE, None)

    samples = list(struct.unpack("<%dh" % (len(frames) // 2), frames))
    samples = lowpass(samples, cutoff, RATE)       # tame harsh highs
    samples = normalize(samples, norm)             # even out / boost level

    # -> 8-bit unsigned (DAC expects 0..255 centred on 128), with clamping.
    return bytes(max(0, min(255, int(round(s)) // 256 + 128)) for s in samples)


def emit(clips):
    lines = [
        "// Auto-generated by tools/wav2c.py -- do not edit. (gitignored)",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define AUDIO_SAMPLE_RATE %d" % RATE,
        "",
        "typedef struct { const char *name; const uint8_t *data; uint32_t len; } audio_clip_t;",
        "",
    ]
    for i, (name, data) in enumerate(clips):
        lines.append("static const uint8_t clip_%d[] = {" % i)
        for j in range(0, len(data), 20):
            lines.append("    " + ",".join(str(b) for b in data[j:j + 20]) + ",")
        lines.append("};")
    lines.append("")
    if clips:
        lines.append("static const audio_clip_t g_audio_clips[] = {")
        for i, (name, data) in enumerate(clips):
            lines.append('    { "%s", clip_%d, %du },' % (name[:20], i, len(data)))
        lines.append("};")
        lines.append("#define AUDIO_CLIP_COUNT ((int)(sizeof(g_audio_clips)/sizeof(g_audio_clips[0])))")
    else:
        lines.append("static const audio_clip_t g_audio_clips[1] = { { \"\", 0, 0 } };")
        lines.append("#define AUDIO_CLIP_COUNT 0")
    lines.append("")
    return "\n".join(lines)


def arg(flag, default, cast):
    return cast(sys.argv[sys.argv.index(flag) + 1]) if flag in sys.argv else default


def main():
    src = sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("-") else "audio_clips"
    out = arg("-o", "main/audio_clips.h", str)
    cutoff = arg("--lowpass", LOWPASS_HZ, int)   # Hz, 0 = off
    norm = arg("--gain", NORMALIZE, float)        # peak target, 0..1

    files = sorted(glob.glob(os.path.join(src, "*.wav")) +
                   glob.glob(os.path.join(src, "*.WAV")))
    clips, total = [], 0
    for f in files:
        try:
            data = convert(f, cutoff, norm)
        except Exception as e:
            print("wav2c: skipping %s (%s)" % (f, e))
            continue
        name = os.path.splitext(os.path.basename(f))[0]
        clips.append((name, data))
        total += len(data)
        print("wav2c: %-20s %6d bytes (%.1fs)" % (name, len(data), len(data) / RATE))

    text = emit(clips)
    # Only rewrite if changed, to avoid recompiling on every build.
    if os.path.exists(out) and open(out).read() == text:
        print("wav2c: %d clip(s), %d bytes -> %s (unchanged)" % (len(clips), total, out))
        return
    with open(out, "w") as fh:
        fh.write(text)
    print("wav2c: %d clip(s), %d bytes -> %s" % (len(clips), total, out))


if __name__ == "__main__":
    main()
