#include "audio.h"
#include "audio_clips.h"   // generated by tools/wav2c.py

#include "driver/dac_continuous.h"
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "esp_log.h"

static const char *TAG = "audio";

static dac_continuous_handle_t s_dac;
static QueueHandle_t           s_queue;    // pending play requests (clip index)
static volatile bool           s_busy;

int audio_clip_count(void) { return AUDIO_CLIP_COUNT; }

const char *audio_clip_name(int index)
{
    return (index >= 0 && index < AUDIO_CLIP_COUNT) ? g_audio_clips[index].name : "";
}

// Lazily bring up the DAC. The boot melody used LEDC on GPIO25; reset the pin so
// the DAC cleanly takes it over (one-way handoff -- no tones after this).
static void dac_init_once(void)
{
    if (s_dac) return;
    gpio_reset_pin(GPIO_NUM_25);

    // 32 KB DMA buffer holds a whole clip (<=2 s @ 16 kHz) in one write, so the
    // write never has to wait for mid-transfer descriptor recycling (that
    // recycling was stalling and timing out on the larger clips).
    dac_continuous_config_t cfg = {
        .chan_mask  = DAC_CHANNEL_MASK_CH0,     // CH0 = GPIO25
        .desc_num   = 16,
        .buf_size   = 2048,
        .freq_hz    = AUDIO_SAMPLE_RATE,
        .offset     = 0,
        // APLL can divide down to audio rates; the default clock can't reach
        // 16 kHz (its mclk divider overflows -> "mclk division exceed 255").
        .clk_src    = DAC_DIGI_CLK_SRC_APLL,
        .chan_mode  = DAC_CHANNEL_MODE_SIMUL,
    };
    if (dac_continuous_new_channels(&cfg, &s_dac) != ESP_OK) {
        ESP_LOGW(TAG, "DAC init failed");
        s_dac = NULL;
        return;
    }
    dac_continuous_enable(s_dac);       // enable ONCE; never cycled (cycling stalled)
    ESP_LOGI(TAG, "DAC ready @ %d Hz", AUDIO_SAMPLE_RATE);
}

// Mid-rail silence (128) written after each clip so the DMA loops silence, not
// the clip's tail.
static const uint8_t s_silence[2048] = { [0 ... 2047] = 128 };

// One long-lived task drains the queue (no per-press task creation). The DAC is
// enabled once and stays running; each clip fits the DMA buffer so writes never
// block on descriptor recycling.
static void audio_task(void *arg)
{
    (void)arg;
    dac_init_once();
    int idx;
    while (xQueueReceive(s_queue, &idx, portMAX_DELAY)) {
        s_busy = true;
        if (s_dac && idx >= 0 && idx < AUDIO_CLIP_COUNT) {
            const audio_clip_t *c = &g_audio_clips[idx];
            ESP_LOGI(TAG, "play '%s' (%u bytes)", c->name, (unsigned)c->len);
            int ms = (int)(c->len / (AUDIO_SAMPLE_RATE / 1000)) + 2000;
            esp_err_t r = dac_continuous_write(s_dac, (uint8_t *)c->data, c->len, NULL, ms);
            if (r != ESP_OK) ESP_LOGW(TAG, "write returned %s", esp_err_to_name(r));
            dac_continuous_write(s_dac, (uint8_t *)s_silence, sizeof(s_silence), NULL, 2000);
        }
        s_busy = false;
    }
}

void audio_play(int index)
{
    if (index < 0 || index >= AUDIO_CLIP_COUNT) return;
    if (s_queue == NULL) {                        // lazy one-time setup
        s_queue = xQueueCreate(2, sizeof(int));
        xTaskCreate(audio_task, "audio", 4096, NULL, 6, NULL);
    }
    if (s_busy) return;                           // play once; ignore while playing
    xQueueSend(s_queue, &index, 0);
}
